//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 02:29:45 PM PDT 
//


package pictureClient.error;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNSUPPORTED_IMAGE_TYPE"/>
 *     &lt;enumeration value="NO_MORE_RECORDS"/>
 *     &lt;enumeration value="INVALID_UPLOAD_OBJECT"/>
 *     &lt;enumeration value="INVALID_CUSTOMER_ID"/>
 *     &lt;enumeration value="INVALID_INDICES"/>
 *     &lt;enumeration value="TEMPORARY_DATABASE_ERROR"/>
 *     &lt;enumeration value="TEMPORARY_IO_ERROR"/>
 *     &lt;enumeration value="EMPTY_UPLOAD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorEnum")
@XmlEnum
public enum ErrorEnum {

    UNSUPPORTED_IMAGE_TYPE,
    NO_MORE_RECORDS,
    INVALID_UPLOAD_OBJECT,
    INVALID_CUSTOMER_ID,
    INVALID_INDICES,
    TEMPORARY_DATABASE_ERROR,
    TEMPORARY_IO_ERROR,
    EMPTY_UPLOAD,
    INVALID_COLUMN,
    DELETE_ERROR;

    public String value() {
        return name();
    }

    public static ErrorEnum fromValue(String v) {
        return valueOf(v);
    }

}
