//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.23 at 02:29:45 PM PDT 
//


package pictureClient.error;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pictureClient.error package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClientErrorResponse_QNAME = new QName("", "clientErrorResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pictureClient.error
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClientErrorResponse }
     * 
     */
    public ClientErrorResponse createClientErrorResponse() {
        return new ClientErrorResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientErrorResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clientErrorResponse")
    public JAXBElement<ClientErrorResponse> createClientErrorResponse(ClientErrorResponse value) {
        return new JAXBElement<ClientErrorResponse>(_ClientErrorResponse_QNAME, ClientErrorResponse.class, null, value);
    }

}
